[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
broadcast = "broadcast"
script = "script"

# Compiler settings
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
revert_strings = "debug"

# Test settings
verbosity = 2
fuzz = { runs = 1000, max_test_rejects = 65536 }
invariant = { runs = 256, depth = 15, fail_on_revert = false, call_override = false }

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]

# Base Network Configuration
[rpc_endpoints]
base = "https://mainnet.base.org"
base_goerli = "https://goerli.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_goerli = { key = "${BASESCAN_API_KEY}", url = "https://api-goerli.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# Environment variables
[env]
PRIVATE_KEY = "${PRIVATE_KEY}"
BASESCAN_API_KEY = "${BASESCAN_API_KEY}"
BASE_RPC_URL = "${BASE_RPC_URL}"
BASE_TESTNET_RPC_URL = "${BASE_TESTNET_RPC_URL}"

# Profile for testing
[profile.test]
verbosity = 3
fuzz = { runs = 10000 }
invariant = { runs = 512, depth = 20 }

# Profile for production deployment
[profile.production]
optimizer = true
optimizer_runs = 1000000
via_ir = true
bytecode_hash = "ipfs"
cbor_metadata = true

# Profile for gas optimization
[profile.gas-optimized]
optimizer = true
optimizer_runs = 10000000
via_ir = true 